### ISSUE TITLE
SDL2-CS.NetCore on Linux?

### ISSUE THREAD

**Issue by m-ghaoui** [flibitijibibo/SDL2-CS#149]
So I've created a new project on Ubuntu 18.04:

```bash
dotnet new console -o myApp
cd myApp
dotnet add package SDL2-CS.NetCore
```

and wrote some code ...

```cs
using System;
using SDL2;

namespace myApp
{
    class Program
    {
        static void Main(string[] args)
        {
            if (SDL.SDL_Init(SDL.SDL_INIT_VIDEO) != 0){
                Console.WriteLine("SDL not initialized!");
            }
        }
    }
}
```

When I try to run it I get this error:

```
moni@moni-ubuntu ~/myApp> dotnet run

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'SDL2.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2.dll: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at myApp.Program.Main(String[] args) in /home/moni/myApp/Program.cs:line 10
```

Does SDL-CS.NetCore support Linux?

(On a side note, SDL2-CS compiles and runs perfectly on MonoDevelop)

**Comment by m-ghaoui** [comment]
Ah! I replaced the nuget version with the git version and it works perfectly!

```bash
moni@moni-ubuntu:~/Projects/myApp$ dotnet remove package SDL2-CS.NetCore
info : Removing PackageReference for package 'SDL2-CS.NetCore' from project '/home/moni/Projects/myApp/myApp.csproj'.

moni@moni-ubuntu:~/Projects/myApp$ dotnet add reference ../SDL2-CS/SDL2-CS.Core.csproj
Reference `..\SDL2-CS\SDL2-CS.Core.csproj` added to the project.

moni@moni-ubuntu:~/Projects/myApp$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /home/moni/Projects/myApp/myApp.csproj...
  Restore completed in 68.05 ms for /home/moni/Projects/SDL2-CS/SDL2-CS.Core.csproj.
  Restore completed in 301.96 ms for /home/moni/Projects/myApp/myApp.csproj.
  SDL2-CS.Core -> /home/moni/Projects/SDL2-CS/bin/Debug/netstandard2.0/SDL2-CS.dll
  myApp -> /home/moni/Projects/myApp/bin/Debug/netcoreapp2.2/myApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.17

moni@moni-ubuntu:~/Projects/myApp$ dotnet run
```
